// Тесты i18n-словарей README (locales/readme/*.json): полнота, согласованность
// RU/EN, целостность плейсхолдеров и доступность через i18n-сервис.
import { describe, expect, it } from "vitest";
import en from "../../core/locales/readme/en.json";
import ru from "../../core/locales/readme/ru.json";
import { i18n } from "../../core/i18n.svelte";

function placeholders(text: string): string[] {
  return Array.from(text.matchAll(/\{(\w+)\}/g), (m) => m[1]).sort();
}

describe("readme i18n dictionaries", () => {
  it("en and ru have identical key sets", () => {
    expect(Object.keys(ru).sort()).toEqual(Object.keys(en).sort());
  });

  it("every value resolves through the i18n service in both locales", () => {
    const enDict = en as Record<string, string>;
    const ruDict = ru as Record<string, string>;
    for (const key of Object.keys(en)) {
      expect(i18n.translateIn("en", key)).toBe(enDict[key]);
      expect(i18n.translateIn("ru", key)).toBe(ruDict[key]);
    }
  });

  it("en and ru values use identical placeholders", () => {
    const enDict = en as Record<string, string>;
    const ruDict = ru as Record<string, string>;
    for (const key of Object.keys(en)) {
      expect(placeholders(ruDict[key])).toEqual(placeholders(enDict[key]));
    }
  });

  it("provides full localized README strings", () => {
    expect(i18n.translateIn("en", "readme.section.overview.title")).toBe("Overview");
    expect(i18n.translateIn("ru", "readme.section.overview.title")).toBe("Обзор");
    expect(i18n.translateIn("en", "readme.generated_by")).toContain("Generated by StackPilot");
    expect(i18n.translateIn("ru", "readme.generated_by")).toContain("Сгенерировано");
  });
});