// Тесты локализованного README: ключи i18n, RU/EN-переводы, детерминизм.
import { describe, expect, it } from "vitest";
import en from "../../core/locales/en";
import ru from "../../core/locales/ru";
import { buildReadme, type ReadmeInput, type ReadmeTranslate } from "./readme";

const dicts: Record<string, Record<string, string>> = { en, ru };

/** Переводчик конкретного словаря БЕЗ кросс-фолбэка: отсутствующий ключ
 *  возвращается как есть — тест сразу видит незаведённый ключ. */
function translator(locale: "en" | "ru"): ReadmeTranslate {
  const dict = dicts[locale];
  return (key, vars) => {
    let text = dict[key] ?? key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        text = text.replace(new RegExp(`\\{\\{${k}\\}\\}`, "g"), String(v));
        text = text.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
      }
    }
    return text;
  };
}

function input(overrides: Partial<ReadmeInput> = {}): ReadmeInput {
  return {
    projectName: "demo-app",
    projectType: { id: "rest-api", labelKey: "wizard.pt.rest_api.label" },
    backendLanguages: [{ id: "python", labelKey: "Python" }],
    frontendLanguages: [{ id: "typescript", labelKey: "TypeScript" }],
    frameworks: [{ id: "nextjs", labelKey: "Next.js" }],
    tools: [{ id: "postgresql", labelKey: "PostgreSQL" }],
    localInfraTools: [],
    architecture: "decoupled",
    features: { docker: true, testing: true, git: true, vscode: true, ci: false },
    ...overrides,
  };
}

describe("buildReadme", () => {
  it("renders English and Russian without unresolved i18n keys", () => {
    const mdEn = buildReadme(input(), translator("en"));
    const mdRu = buildReadme(input(), translator("ru"));

    expect(mdEn).toContain("## Overview");
    expect(mdEn).toContain("Generated by StackPilot");
    expect(mdEn).not.toContain("create.readme.doc.");

    expect(mdRu).toContain("## Обзор");
    expect(mdRu).toContain("Сгенерировано StackPilot");
    expect(mdRu).not.toContain("create.readme.doc.");
  });

  it("keeps stack data and project name in both locales", () => {
    for (const locale of ["en", "ru"] as const) {
      const md = buildReadme(input(), translator(locale));
      expect(md).toContain("demo-app");
      expect(md).toContain("Python");
      expect(md).toContain("Next.js");
      expect(md).toContain("PostgreSQL");
    }
  });

  it("substitutes all placeholders", () => {
    const md = buildReadme(input(), translator("ru"));
    expect(md).not.toContain("{name}");
    expect(md).not.toContain("{stack}");
    expect(md).not.toContain("{type}");
    expect(md).not.toContain("{list}");
  });

  it("is deterministic", () => {
    const first = buildReadme(input(), translator("en"));
    const second = buildReadme(input(), translator("en"));
    expect(first).toBe(second);
  });

  it("includes optional sections only when the feature is on", () => {
    const minimal = buildReadme(
      input({
        tools: [],
        localInfraTools: [],
        features: { docker: false, testing: false, git: false, vscode: false, ci: false },
      }),
      translator("en"),
    );
    expect(minimal).not.toContain("## Docker");
    expect(minimal).not.toContain("## Testing");
    expect(minimal).not.toContain("## Environment variables");
    expect(minimal).toContain("## Next steps");
  });
});
